name: "Merge guide template"
description: "Merge upstream changes from the base 18F guide template"

# To avoid merge conflicts, use a strategy of first adopting all changes from
# the upstream template, then reverting files and directories mangaged by the
# the downstream guide.
# Note: GitHub Actions do not execute with `workflows` permission; any workflow
# updates that should be reflected in downstream guides must be manually merged.
runs:
  using: "composite"
  steps:
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add -f upstream "https://github.com/18F/isildurs-bane.git"
        git merge --squash --strategy-option=theirs --allow-unrelated-histories upstream/main
        git restore --source=HEAD --staged --worktree -- _guide
        git restore --source=HEAD --staged --worktree -- README.md
        git restore --source=HEAD --staged --worktree -- .github/workflows
        REMOTE_SHA=`git rev-parse upstream/main`
        git diff-index --quiet --cached HEAD -- || \
          git commit -m "Merging in 18F/isildurs-bane guide template" -m "18F/isildurs-bane@$REMOTE_SHA"
        git push
      shell: bash
